### ISSUE TITLE
tra seem to be wrt dicom origin rather than 'autoscoper' origin

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#102] opened 2024-06-06 20:20 UTC
When generating VRG from a static volume or from a seqence, the Origin2DICOM transform represents relationship between dicom space and aut space.

| Dicom space |  Origin2DICOM used to express volume in AUT space 
|--|--|
| ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/9d1aeb87-ead3-419b-a293-01e236f68e4d) | ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/95592659-841b-4903-a6a8-40b1ca16091f) |

:warning: AUT space (center of volume and VRGs) is the space from which .tra transforms should be expressed. Taking  .tra : the positions are not in appropriate anatomical location. See below.

| AUT space (center of volume and VRGs) is the space from which .tra transforms should be expressed. Taking  .tra : the positions are not in appropriate anatomical location | @NicerNewerCar pointed- they appear translationaly to be in DICOM basis: |
|--|--|
| ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/a58d2579-1336-43cc-99d4-36e79bddb2b8) | ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/1a76441a-ec5c-4067-bf6f-6b298fcb8222) |

**Comment by amymmorton** [comment] 2024-06-13 14:22
Attempting to branch at commit 9950058, mar 28th just before commit 24c43b6 

![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/e7b80b45-21e3-4560-964a-f2b3fc04c281)

**Comment by amymmorton** [comment] 2024-06-13 15:06
unfortunately in that bracnh build the origin2dicom tfm was not being generated for either a static 3d ct or the seq volume

![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/6f0768e1-bd91-44ae-9c26-5ea3103e38a4)

**Comment by jcfr** [comment] 2024-06-18 20:48
Based on https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/102#issuecomment-2165950975 from @amymmorton , regression possibly introduced through pull request:
* https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/68

originally intended to address:
* https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/56

**Comment by jcfr** [comment] 2024-06-18 20:56
@amymmorton To allow me to more easily reproduce the problem, would it be possible to provide  the steps & input files allowing to reproduce the problem in SlicerAutoscoperM ?

**Comment by amymmorton** [comment] 2024-06-19 15:02
Originally shared in email from @NicerNewerCar 

[Autoscoper ](https://drive.google.com/file/d/1KwaSS67CsZQSn58qlWSJaytAuWrWpzZ0/view?usp=drive_web)
[Slicer Scene](https://drive.google.com/file/d/153kA8IkkUlUD3AzL7xJF5uxoDvtk1cRG/view?usp=drive_web)

**Comment by amymmorton** [comment] 2024-06-19 15:10
The data originally pprovided 4/29:  [BN00107](https://drive.google.com/file/d/1Gy3vnLp-tPiQ80VqL2fEsx5cE-iyAkoi/view?usp=sharing)

**Comment by amymmorton** [comment] 2024-06-19 19:40
Something odd about Origin2DICOM

when applied to the 'target' pose CT dicoms- the origin should be geometric center in the volume- but it's not:

![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/03a55e99-2b29-43e3-84d9-308b8cc8e342)

yellow is neutral - bone color rendering is flexion with Origin2DICOM applied

**Comment by NicerNewerCar** [comment] 2024-06-20 13:40
> Something odd about Origin2DICOM
> 
> when applied to the 'target' pose CT dicoms- the origin should be geometric center in the volume- but it's not:

This is happening because the Origin2Dicom Transform is created from the `1: neutral` volume. The `4: flexion` volume has a smaller Z dimension and because of that ends up slightly off center from the origin in the z direction.

# 

It Looks like the Origin2Dicom is not getting applied correctly or is getting removed before/during the VRG generation.

| Slicer No O2D tfm | Slicer O2D | Autoscoper |
| -------------------- | ---------- | ------------| 
| ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/56621c9a-8478-40c9-9869-ed4f26147f46) | ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/ffbdac09-69dc-4fe1-bb7a-6e45adf6e08f) | ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/8450e5de-0596-4d32-8884-95042c0fef0d) |

Working on a fix for this now

**Closed** 2024-07-17 20:08 UTC
