### ISSUE TITLE
Automatic camera placement for 4DCT

### ISSUE THREAD

**Issue by vforcesar** [BrownBiomechanics/SlicerAutoscoperM#105] opened 2024-06-21 18:11 UTC
Hi, It looks like the automatic camera placement feature doesn't work for my data. It always the error below
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/132497790/729379c5-91dc-46c2-8b18-34ac03bfc32a)

**Comment by NicerNewerCar** [comment] 2024-06-21 19:48
To reproduce run any previously centered (and hardened) volume through the 3DCT / Seq 3D & 4DCT pipelines

**Comment by amymmorton** [comment] 2024-09-25 16:26
since this projection branch is depreciated in favor of #99 - suggest closing

**Closed by amymmorton** 2024-09-25 16:26 UTC
